package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private Long codigoArti;
     private Usuarios usuarios;
     private String nombre;
     private String descripcion;
     private String autor;
     private Date fechaCreacion;
     private Date fechaModifcacion;
     private String usuCrea;
     private String usuModifica;
     private String estadoRegistro;
     private Set<Anexos> anexoses = new HashSet<Anexos>(0);
     private Set<CategoriasArticulos> categoriasArticuloses = new HashSet<CategoriasArticulos>(0);
     private Set<EventosArticulos> eventosArticuloses = new HashSet<EventosArticulos>(0);

    public Articulos() {
    }

	
    public Articulos(Long codigoArti, Usuarios usuarios, String nombre, String descripcion, String autor, Date fechaCreacion, String usuCrea, String estadoRegistro) {
        this.codigoArti = codigoArti;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.autor = autor;
        this.fechaCreacion = fechaCreacion;
        this.usuCrea = usuCrea;
        this.estadoRegistro = estadoRegistro;
    }
    public Articulos(Long codigoArti, Usuarios usuarios, String nombre, String descripcion, String autor, Date fechaCreacion, Date fechaModifcacion, String usuCrea, String usuModifica, String estadoRegistro, Set<Anexos> anexoses, Set<CategoriasArticulos> categoriasArticuloses, Set<EventosArticulos> eventosArticuloses) {
       this.codigoArti = codigoArti;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.autor = autor;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifcacion = fechaModifcacion;
       this.usuCrea = usuCrea;
       this.usuModifica = usuModifica;
       this.estadoRegistro = estadoRegistro;
       this.anexoses = anexoses;
       this.categoriasArticuloses = categoriasArticuloses;
       this.eventosArticuloses = eventosArticuloses;
    }
   
    public Long getCodigoArti() {
        return this.codigoArti;
    }
    
    public void setCodigoArti(Long codigoArti) {
        this.codigoArti = codigoArti;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModifcacion() {
        return this.fechaModifcacion;
    }
    
    public void setFechaModifcacion(Date fechaModifcacion) {
        this.fechaModifcacion = fechaModifcacion;
    }
    public String getUsuCrea() {
        return this.usuCrea;
    }
    
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }
    public String getUsuModifica() {
        return this.usuModifica;
    }
    
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<Anexos> getAnexoses() {
        return this.anexoses;
    }
    
    public void setAnexoses(Set<Anexos> anexoses) {
        this.anexoses = anexoses;
    }
    public Set<CategoriasArticulos> getCategoriasArticuloses() {
        return this.categoriasArticuloses;
    }
    
    public void setCategoriasArticuloses(Set<CategoriasArticulos> categoriasArticuloses) {
        this.categoriasArticuloses = categoriasArticuloses;
    }
    public Set<EventosArticulos> getEventosArticuloses() {
        return this.eventosArticuloses;
    }
    
    public void setEventosArticuloses(Set<EventosArticulos> eventosArticuloses) {
        this.eventosArticuloses = eventosArticuloses;
    }




}


