package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Colecciones generated by hbm2java
 */
public class Colecciones  implements java.io.Serializable {


     private Long codigoCole;
     private Usuarios usuarios;
     private String nombre;
     private Set<ColeccionesRss> coleccionesRsses = new HashSet<ColeccionesRss>(0);

    public Colecciones() {
    }

	
    public Colecciones(Long codigoCole, Usuarios usuarios, String nombre) {
        this.codigoCole = codigoCole;
        this.usuarios = usuarios;
        this.nombre = nombre;
    }
    public Colecciones(Long codigoCole, Usuarios usuarios, String nombre, Set<ColeccionesRss> coleccionesRsses) {
       this.codigoCole = codigoCole;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.coleccionesRsses = coleccionesRsses;
    }
   
    public Long getCodigoCole() {
        return this.codigoCole;
    }
    
    public void setCodigoCole(Long codigoCole) {
        this.codigoCole = codigoCole;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<ColeccionesRss> getColeccionesRsses() {
        return this.coleccionesRsses;
    }
    
    public void setColeccionesRsses(Set<ColeccionesRss> coleccionesRsses) {
        this.coleccionesRsses = coleccionesRsses;
    }




}


