package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Long codigoRol;
     private String nombreRol;
     private Date fechaCreacion;
     private Date fechaModifcacion;
     private String usuCrea;
     private String usuModifica;
     private String estadoRegistro;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Roles() {
    }

	
    public Roles(Long codigoRol, String nombreRol, Date fechaCreacion, String usuCrea, String estadoRegistro) {
        this.codigoRol = codigoRol;
        this.nombreRol = nombreRol;
        this.fechaCreacion = fechaCreacion;
        this.usuCrea = usuCrea;
        this.estadoRegistro = estadoRegistro;
    }
    public Roles(Long codigoRol, String nombreRol, Date fechaCreacion, Date fechaModifcacion, String usuCrea, String usuModifica, String estadoRegistro, Set<Usuarios> usuarioses) {
       this.codigoRol = codigoRol;
       this.nombreRol = nombreRol;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifcacion = fechaModifcacion;
       this.usuCrea = usuCrea;
       this.usuModifica = usuModifica;
       this.estadoRegistro = estadoRegistro;
       this.usuarioses = usuarioses;
    }
   
    public Long getCodigoRol() {
        return this.codigoRol;
    }
    
    public void setCodigoRol(Long codigoRol) {
        this.codigoRol = codigoRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModifcacion() {
        return this.fechaModifcacion;
    }
    
    public void setFechaModifcacion(Date fechaModifcacion) {
        this.fechaModifcacion = fechaModifcacion;
    }
    public String getUsuCrea() {
        return this.usuCrea;
    }
    
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }
    public String getUsuModifica() {
        return this.usuModifica;
    }
    
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


