package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0



/**
 * Anexos generated by hbm2java
 */
public class Anexos  implements java.io.Serializable {


     private Long codigoAnexo;
     private Articulos articulos;
     private String nombre;
     private String url;
     private String formato;

    public Anexos() {
    }

	
    public Anexos(Long codigoAnexo, Articulos articulos, String nombre, String formato) {
        this.codigoAnexo = codigoAnexo;
        this.articulos = articulos;
        this.nombre = nombre;
        this.formato = formato;
    }
    public Anexos(Long codigoAnexo, Articulos articulos, String nombre, String url, String formato) {
       this.codigoAnexo = codigoAnexo;
       this.articulos = articulos;
       this.nombre = nombre;
       this.url = url;
       this.formato = formato;
    }
   
    public Long getCodigoAnexo() {
        return this.codigoAnexo;
    }
    
    public void setCodigoAnexo(Long codigoAnexo) {
        this.codigoAnexo = codigoAnexo;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }




}


