package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * CategoriasArticulos generated by hbm2java
 */
public class CategoriasArticulos  implements java.io.Serializable {


     private Long codigoCateArti;
     private Categorias categorias;
     private Articulos articulos;
     private Date fechaCreacion;
     private Date fechaModifcacion;
     private String usuCrea;
     private String usuModifica;
     private String estadoRegistro;

    public CategoriasArticulos() {
    }

	
    public CategoriasArticulos(Long codigoCateArti, Categorias categorias, Articulos articulos, String usuCrea, String estadoRegistro) {
        this.codigoCateArti = codigoCateArti;
        this.categorias = categorias;
        this.articulos = articulos;
        this.usuCrea = usuCrea;
        this.estadoRegistro = estadoRegistro;
    }
    public CategoriasArticulos(Long codigoCateArti, Categorias categorias, Articulos articulos, Date fechaCreacion, Date fechaModifcacion, String usuCrea, String usuModifica, String estadoRegistro) {
       this.codigoCateArti = codigoCateArti;
       this.categorias = categorias;
       this.articulos = articulos;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifcacion = fechaModifcacion;
       this.usuCrea = usuCrea;
       this.usuModifica = usuModifica;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getCodigoCateArti() {
        return this.codigoCateArti;
    }
    
    public void setCodigoCateArti(Long codigoCateArti) {
        this.codigoCateArti = codigoCateArti;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModifcacion() {
        return this.fechaModifcacion;
    }
    
    public void setFechaModifcacion(Date fechaModifcacion) {
        this.fechaModifcacion = fechaModifcacion;
    }
    public String getUsuCrea() {
        return this.usuCrea;
    }
    
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }
    public String getUsuModifica() {
        return this.usuModifica;
    }
    
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


