package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Long codigoCate;
     private String nombre;
     private Date fechaCreacion;
     private Date fechaModifcacion;
     private String usuCrea;
     private String usuModifica;
     private String estadoRegistro;
     private Set<CategoriasArticulos> categoriasArticuloses = new HashSet<CategoriasArticulos>(0);

    public Categorias() {
    }

	
    public Categorias(Long codigoCate, String nombre, Date fechaCreacion, String usuCrea, String estadoRegistro) {
        this.codigoCate = codigoCate;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.usuCrea = usuCrea;
        this.estadoRegistro = estadoRegistro;
    }
    public Categorias(Long codigoCate, String nombre, Date fechaCreacion, Date fechaModifcacion, String usuCrea, String usuModifica, String estadoRegistro, Set<CategoriasArticulos> categoriasArticuloses) {
       this.codigoCate = codigoCate;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifcacion = fechaModifcacion;
       this.usuCrea = usuCrea;
       this.usuModifica = usuModifica;
       this.estadoRegistro = estadoRegistro;
       this.categoriasArticuloses = categoriasArticuloses;
    }
   
    public Long getCodigoCate() {
        return this.codigoCate;
    }
    
    public void setCodigoCate(Long codigoCate) {
        this.codigoCate = codigoCate;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModifcacion() {
        return this.fechaModifcacion;
    }
    
    public void setFechaModifcacion(Date fechaModifcacion) {
        this.fechaModifcacion = fechaModifcacion;
    }
    public String getUsuCrea() {
        return this.usuCrea;
    }
    
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }
    public String getUsuModifica() {
        return this.usuModifica;
    }
    
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<CategoriasArticulos> getCategoriasArticuloses() {
        return this.categoriasArticuloses;
    }
    
    public void setCategoriasArticuloses(Set<CategoriasArticulos> categoriasArticuloses) {
        this.categoriasArticuloses = categoriasArticuloses;
    }




}


