package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Entradas generated by hbm2java
 */
public class Entradas  implements java.io.Serializable {


     private Long codigoEntra;
     private Rss rss;
     private String favorito;
     private Date fechaFavorito;
     private String leido;
     private Date fechaLeido;

    public Entradas() {
    }

	
    public Entradas(Long codigoEntra, Rss rss, String favorito, String leido) {
        this.codigoEntra = codigoEntra;
        this.rss = rss;
        this.favorito = favorito;
        this.leido = leido;
    }
    public Entradas(Long codigoEntra, Rss rss, String favorito, Date fechaFavorito, String leido, Date fechaLeido) {
       this.codigoEntra = codigoEntra;
       this.rss = rss;
       this.favorito = favorito;
       this.fechaFavorito = fechaFavorito;
       this.leido = leido;
       this.fechaLeido = fechaLeido;
    }
   
    public Long getCodigoEntra() {
        return this.codigoEntra;
    }
    
    public void setCodigoEntra(Long codigoEntra) {
        this.codigoEntra = codigoEntra;
    }
    public Rss getRss() {
        return this.rss;
    }
    
    public void setRss(Rss rss) {
        this.rss = rss;
    }
    public String getFavorito() {
        return this.favorito;
    }
    
    public void setFavorito(String favorito) {
        this.favorito = favorito;
    }
    public Date getFechaFavorito() {
        return this.fechaFavorito;
    }
    
    public void setFechaFavorito(Date fechaFavorito) {
        this.fechaFavorito = fechaFavorito;
    }
    public String getLeido() {
        return this.leido;
    }
    
    public void setLeido(String leido) {
        this.leido = leido;
    }
    public Date getFechaLeido() {
        return this.fechaLeido;
    }
    
    public void setFechaLeido(Date fechaLeido) {
        this.fechaLeido = fechaLeido;
    }




}


