package co.edu.usbcali.lookdocs.model;
// Generated 27-feb-2015 15:10:55 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Long codigoUsua;
     private Roles roles;
     private String nombre;
     private String clave;
     private String email;
     private Date fechaCreacion;
     private Date fechaModifcacion;
     private String usuCrea;
     private String usuModifica;
     private String estadoRegistro;
     private Set<Colecciones> coleccioneses = new HashSet<Colecciones>(0);
     private Set<Articulos> articuloses = new HashSet<Articulos>(0);
     private Set<EventosArticulos> eventosArticuloses = new HashSet<EventosArticulos>(0);

    public Usuarios() {
    }

	
    public Usuarios(Long codigoUsua, Roles roles, String nombre, String clave, String email, Date fechaCreacion, String usuCrea, String estadoRegistro) {
        this.codigoUsua = codigoUsua;
        this.roles = roles;
        this.nombre = nombre;
        this.clave = clave;
        this.email = email;
        this.fechaCreacion = fechaCreacion;
        this.usuCrea = usuCrea;
        this.estadoRegistro = estadoRegistro;
    }
    public Usuarios(Long codigoUsua, Roles roles, String nombre, String clave, String email, Date fechaCreacion, Date fechaModifcacion, String usuCrea, String usuModifica, String estadoRegistro, Set<Colecciones> coleccioneses, Set<Articulos> articuloses, Set<EventosArticulos> eventosArticuloses) {
       this.codigoUsua = codigoUsua;
       this.roles = roles;
       this.nombre = nombre;
       this.clave = clave;
       this.email = email;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifcacion = fechaModifcacion;
       this.usuCrea = usuCrea;
       this.usuModifica = usuModifica;
       this.estadoRegistro = estadoRegistro;
       this.coleccioneses = coleccioneses;
       this.articuloses = articuloses;
       this.eventosArticuloses = eventosArticuloses;
    }
   
    public Long getCodigoUsua() {
        return this.codigoUsua;
    }
    
    public void setCodigoUsua(Long codigoUsua) {
        this.codigoUsua = codigoUsua;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModifcacion() {
        return this.fechaModifcacion;
    }
    
    public void setFechaModifcacion(Date fechaModifcacion) {
        this.fechaModifcacion = fechaModifcacion;
    }
    public String getUsuCrea() {
        return this.usuCrea;
    }
    
    public void setUsuCrea(String usuCrea) {
        this.usuCrea = usuCrea;
    }
    public String getUsuModifica() {
        return this.usuModifica;
    }
    
    public void setUsuModifica(String usuModifica) {
        this.usuModifica = usuModifica;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<Colecciones> getColeccioneses() {
        return this.coleccioneses;
    }
    
    public void setColeccioneses(Set<Colecciones> coleccioneses) {
        this.coleccioneses = coleccioneses;
    }
    public Set<Articulos> getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set<Articulos> articuloses) {
        this.articuloses = articuloses;
    }
    public Set<EventosArticulos> getEventosArticuloses() {
        return this.eventosArticuloses;
    }
    
    public void setEventosArticuloses(Set<EventosArticulos> eventosArticuloses) {
        this.eventosArticuloses = eventosArticuloses;
    }




}


